### PR TITLE
Some wasm updates

### PR DESCRIPTION
**Pull request by a-omsk**
generated new wasm binary and gluecode with:

latest jq master branch
latest oniguruma master branch
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.32 (WebAssembly.instantiateStreaming support added)

+ added .trim() to stdout output in raw method

### CODE REVIEW

**Comment by fiatjaf** [comment]
Does it work?

**Comment by a-omsk** [comment]
@fiatjaf yeah, and pass the tests in Travis CI

**Comment by fiatjaf** [comment]
Those tests only use the `jq.js` version, the only file you didn't generate.
But if you say it is good, then it is good.

**Comment by a-omsk** [comment]
@fiatjaf can you bump the npm version with this changes?

**Comment by fiatjaf** [comment]
Done.

Sorry for taking so long. Thank you!

**Pull request merged**
