### PR TITLE
fix jq main options: reset in main

### PR DESCRIPTION
**Pull request by yurenchen000**
the jq/src/main.c
has a global variable `options`, which can't be reset at js.

so I add a main.patch for `options` reset

#15

### CODE REVIEW

**Comment by fiatjaf** [comment]
I don't get it, why do you want to reset it? Does this break anything?

**Comment by yurenchen000** [comment]
sorry for late response,
I explain it here:

https://github.com/fiatjaf/jq-web/issues/15#issue-559966849
https://github.com/fiatjaf/jq-web/issues/15#issuecomment-1627655318

**Comment by fiatjaf** [comment]
I don't know how to compile this to wasm anymore, the emscripten interface has changed too much.

If you know how to and want to help me, please tell me what I must do, or maybe you can setup a script to build these things and push them to npm.

**Comment by yurenchen000** [comment]
LMAO, I just follow your README.md to build it
https://github.com/fiatjaf/jq-web#build

I don't known how to upload npm, I just say what steps I compile it (same as README):

## install emsdk
```sh
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk

./emsdk install 1.38.45
./emsdk activate 1.38.45
cd ..
```
## compile
```sh
git clone git@github.com:fiatjaf/jq-web.git
cd jq-web

source ../emsdk/emsdk_env.sh
make
```

then got jq.* things:
```
jq.asm.bundle.js
jq.asm.bundle.min.js
jq.asm.js
jq.asm.js.mem
jq.asm.min.js
jq.wasm.js
jq.wasm.min.js
jq.wasm.wasm
```

access index.html (via web server) can try it.

**Pull request merged**
